import { createHash } from "crypto";

// All 55 license keys — hashed and stored in database on first run
const KEYS = [
  "FINTEL-DG6X-XTPT-GDWD","FINTEL-XZ9D-PJVG-SGUF","FINTEL-H367-K5D4-R4WQ","FINTEL-EZC5-Z8GC-LRRJ",
  "FINTEL-7BB4-N3LR-P3TX","FINTEL-BF7R-AXN3-K3H2","FINTEL-73N8-L5EB-C5VM","FINTEL-XEYK-Q22C-UFF3",
  "FINTEL-FX2L-ZXCS-FLVP","FINTEL-RCAH-RM48-UB7Y","FINTEL-9RVZ-JQN9-KWHL","FINTEL-ZC3V-KFMV-UJZZ",
  "FINTEL-VLWM-YEVP-LEPJ","FINTEL-ALE9-5CWY-4VQM","FINTEL-N8XG-HUSZ-BNAF","FINTEL-7724-GGWA-J88W",
  "FINTEL-YNZU-4AGB-9768","FINTEL-R6D4-ETNV-GN6M","FINTEL-YERR-PYQG-EKB2","FINTEL-AQMU-QPFG-4S2S",
  "FINTEL-U9QM-ZHCP-VRN2","FINTEL-QAJE-DHEZ-NQ2L","FINTEL-FQNT-26AQ-TKMB","FINTEL-HG5V-YYFU-4WVS",
  "FINTEL-8RJM-HZ7S-WU59","FINTEL-FB3J-7AT5-3FZ9","FINTEL-B39B-QSMC-S2X4","FINTEL-LJNS-ZZ5T-UXT4",
  "FINTEL-E4LH-DA74-LC25","FINTEL-J9W3-UVCQ-9B2J","FINTEL-5CVV-G7UM-MVJ7","FINTEL-92BA-HTAR-L3M3",
  "FINTEL-AM22-NXL9-Z6ZG","FINTEL-SD3Z-K6T3-5DWZ","FINTEL-ZNDN-P2VE-4G55","FINTEL-9UCN-BNSN-L75J",
  "FINTEL-Y86R-46G3-HYLG","FINTEL-3QK3-A96J-H4ME","FINTEL-9Z7U-2QTK-APE2","FINTEL-XWRA-JSNU-S3YC",
  "FINTEL-DXQV-RTRS-9DKB","FINTEL-NNRV-L9UG-AQ49","FINTEL-SSGF-YDDU-8LB8","FINTEL-KHUZ-74PL-NXQB",
  "FINTEL-EHKU-FHCW-NY75","FINTEL-2TSH-YP7B-3PF8","FINTEL-9E2W-FVNW-NHPX","FINTEL-TV9J-DT2U-XMU2",
  "FINTEL-3F9K-HQM2-SNZ8","FINTEL-SCZB-UEG7-RNU6","FINTEL-67C5-HFFJ-6DM7","FINTEL-JEJM-LC7Q-TE9E",
  "FINTEL-6LNE-K4U6-D48E","FINTEL-W3LH-6ER7-JAVK","FINTEL-QB73-Z3XX-VKVG"
];

export function getKeyHashes(): string[] {
  return KEYS.map(k => createHash("sha256").update(k.trim().toUpperCase()).digest("hex"));
}

export function hashKey(key: string): string {
  return createHash("sha256").update(key.trim().toUpperCase()).digest("hex");
}
